language: node_js
sudo: false
node_js:
  - "8"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - npm install
  - npm run lint
  - npm test
  - cd tests/node.js && node validate-dictionary.js
