language: node_js
sudo: false
node_js:
  - "8"

addons:
  firefox: "58.0"

services:
  - xvfb

before_script:
  - "export DISPLAY=:99.0"
  - sleep 3 # give xvfb some time to start

# Tests for Chrome do not work on Travis CI
# (they can work, but with lots of constraints...
# it is not worth the effort).
script:
  - npm install
  - npm run lint
  - npm run test-firefox
  - cd tests/node.js && node validate-dictionary.js
