language: node_js
sudo: true
node_js:
  - "8"

addons:
  - firefox: "58.0"
  - chrome: stable

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - npm install
  - npm run lint
  - npm test
  - cd tests/node.js && node validate-dictionary.js
